function DrawText2D(x,y,scale,font,text,r,g,b,a)
    SetTextFont(font)
    SetTextProportional(0)
    SetTextScale(scale, scale)
    SetTextColour(r, g, b, a)
    SetTextDropShadow(0, 0, 0, 0,255)
    SetTextEdge(1, 0, 0, 0, 255)
    SetTextDropShadow()
    SetTextOutline()
    SetTextEntry("STRING")
    AddTextComponentString(text)
    DrawText(x , y)
end

Bones = {
    [0x0] = "Chest",
    [0xE0FD] = "Chest",
    [0x5C01] = "Chest",
    [0x60F0] = "Chest",
    [0x60F1] = "Chest",
    [0x60F2] = "Chest",
    [0xFCD9] = "Chest",
    [0xB1C5] = "Chest",
    [0xEEEB] = "Chest",
    [0x49D9] = "Chest",
    [0x67F2] = "Chest",
    [0xFF9] = "Chest",
    [0xFFA] = "Chest",
    [0x67F3] = "Chest",
    [0x1049] = "Chest",
    [0x104A] = "Chest",
    [0x67F4] = "Chest",
    [0x1059] = "Chest",
    [0x105A] = "Chest",
    [0x67F5] = "Chest",
    [0x1029] = "Chest",
    [0x102A] = "Chest",
    [0x67F6] = "Chest",
    [0x1039] = "Chest",
    [0x103A] = "Chest",
    [0x29D2] = "Chest",
    [0x9D4D] = "Chest",
    [0x6E5C] = "Chest",
    [0xDEAD] = "Chest",
    [0xE5F2] = "Chest",
    [0xFA10] = "Chest",
    [0xFA11] = "Chest",
    [0xE5F3] = "Chest",
    [0xFA60] = "Chest",
    [0xFA61] = "Chest",
    [0xE5F4] = "Chest",
    [0xFA70] = "Chest",
    [0xFA71] = "Chest",
    [0xE5F5] = "Chest",
    [0xFA40] = "Chest",
    [0xFA41] = "Chest",
    [0xE5F6] = "Chest",
    [0xFA50] = "Chest",
    [0xFA51] = "Chest",
    [0x9995] = "Chest",
    [0x2E28] = "Legs",
    [0xE39F] = "Legs",
    [0xF9BB] = "Legs",
    [0x3779] = "Legs",
    [0x83C] = "Legs",
    [0xCA72] = "Legs",
    [0x9000] = "Legs",
    [0xCC4D] = "Legs",
    [0x512D] = "Legs",
    [0x796E] = "Head"
}

Weapons = {
    [`WEAPON_BAT`] = "Melee",
    [`WEAPON_DAGGER`] = "Melee",
    [`WEAPON_BOTTLE`] = "Melee",
    [`WEAPON_UNARMED`] = "Melee",
    [`WEAPON_FLASHLIGHT`] = "Melee",
    [`WEAPON_GOLFCLUB`] = "Melee",
    [`WEAPON_HAMMER`] = "Melee",
    [`WEAPON_HATCHET`] = "Melee",
    [`WEAPON_KNUCKLE`] = "Melee",
    [`WEAPON_KNIFE`] = "Melee",
    [`WEAPON_MACHETE`] = "Melee",
    [`WEAPON_SWITCHBLADE`] = "Melee",
    [`WEAPON_NIGHTSTICK`] = "Melee",
    [`WEAPON_WRENCH`] = "Melee",
    [`WEAPON_BATTLEAXE`] = "Melee",
    [`WEAPON_POOLCUE`] = "Melee",
    [`WEAPON_STONE_HATCHET`] = "Melee",

    [`WEAPON_PISTOL`] = "Pistol",
    [`WEAPON_PISTOL_MK2`] = "Pistol",
    [`WEAPON_COMBATPISTOL`] = "Pistol",
    [`WEAPON_APPISTOL`] = "Pistol",
    [`WEAPON_STUNGUN`] = "Pistol",
    [`WEAPON_PISTOL50`] = "Pistol",
    [`WEAPON_SNSPISTOL`] = "Pistol",
    [`WEAPON_SNSPISTOL_MK2`] = "Pistol",
    [`WEAPON_HEAVYPISTOL`] = "Pistol",
    [`WEAPON_VINTAGEPISTOL`] = "Pistol",
    [`WEAPON_MARKSMANPISTOL`] = "Pistol",
    [`WEAPON_REVOLVER`] = "Pistol",
    [`WEAPON_REVOLVER_MK2`] = "Pistol",
    [`WEAPON_DOUBLEACTION`] = "Pistol",
    [`WEAPON_CERAMICPISTOL`] = "Pistol",
    [`WEAPON_NAVYREVOLVER`] = "Pistol",

    [`WEAPON_MICROSMG`] = "SMG",
    [`WEAPON_SMG`] = "SMG",
    [`WEAPON_SMG_MK2`] = "SMG",
    [`WEAPON_ASSAULTSMG`] = "SMG",
    [`WEAPON_COMBATPDW`] = "SMG",
    [`WEAPON_MACHINEPISTOL`] = "SMG",
    [`WEAPON_MINISMG`] = "SMG",

    [`WEAPON_PUMPSHOTGUN`] = "Shotgun",
    [`WEAPON_PUMPSHOTGUN_MK2`] = "Shotgun",
    [`WEAPON_SAWNOFFSHOTGUN`] = "Shotgun",
    [`WEAPON_ASSAULTSHOTGUN`] = "Shotgun",
    [`WEAPON_BULLPUPSHOTGUN`] = "Shotgun",
    [`WEAPON_MUSKET`] = "Shotgun",
    [`WEAPON_HEAVYSHOTGUN`] = "Shotgun",
    [`WEAPON_DBSHOTGUN`] = "Shotgun",
    [`WEAPON_AUTOSHOTGUN`] = "Shotgun",

    [`WEAPON_ASSAULTRIFLE`] = "Rifle",
    [`WEAPON_ASSAULTRIFLE_MK2`] = "Rifle",
    [`WEAPON_CARBINERIFLE`] = "Rifle",
    [`WEAPON_CARBINERIFLE_MK2`] = "Rifle",
    [`WEAPON_ADVANCEDRIFLE`] = "Rifle",
    [`WEAPON_SPECIALCARBINE`] = "Rifle",
    [`WEAPON_SPECIALCARBINE_MK2`] = "Rifle",
    [`WEAPON_BULLPUPRIFLE`] = "Rifle",
    [`WEAPON_BULLPUPRIFLE_MK2`] = "Rifle",
    [`WEAPON_COMPACTRIFLE`] = "Rifle",
    [`WEAPON_MG`] = "Rifle",
    [`WEAPON_COMBATMG`] = "Rifle",
    [`WEAPON_COMBATMG_MK2`] = "Rifle",
    [`WEAPON_GUSENBERG`] = "Rifle",

    [`WEAPON_SNIPERRIFLE`] = "Sniper",
    [`WEAPON_HEAVYSNIPER`] = "Sniper",
    [`WEAPON_HEAVYSNIPER_MK2`] = "Sniper",
    [`WEAPON_MARKSMANRIFLE`] = "Sniper",
    [`WEAPON_MARKSMANRIFLE_MK2`] = "Sniper",

    [`WEAPON_RAYPISTOL`] = "Special",
    [`WEAPON_RAYCARBINE`] = "Special",
    [`WEAPON_MINIGUN`] = "Special",
    [`WEAPON_RAILGUN`] = "Special",
    [`WEAPON_RAYMINIGUN`] = "Special",
}

Draw = {
    ["Dealt"] = {
        [1] = 0.9,
        [2] = 0.873,
        [3] = 0.838,
        [4] = 0.8965,
        [5] = 0.937,
        [6] = 0.838,
        [7] = 0.8965,
        [8] = 0.945,
        [9] = 0.838,
        [10] = 0.8965,
        [11] = 0.945,
        [12] = 0.838,
        [13] = 0.8965,
        [14] = 0.945,
        [15] = 0.838,
        [16] = 0.8965,
        [17] = 0.945,
        [18] = 0.838,
        [19] = 0.8965,
        [20] = 0.94
    },

    ["Taken"] = {
        [1] = 0.1,
        [2] = 0.073,
        [3] = 0.038,
        [4] = 0.0965,
        [5] = 0.137,
        [6] = 0.038,
        [7] = 0.0965,
        [8] = 0.145,
        [9] = 0.038,
        [10] = 0.0965,
        [11] = 0.145,
        [12] = 0.038,
        [13] = 0.0965,
        [14] = 0.145,
        [15] = 0.038,
        [16] = 0.0965,
        [17] = 0.145,
        [18] = 0.038,
        [19] = 0.0965,
        [20] = 0.14
    },
}